### ISSUE TITLE
tag update needed 

### ISSUE THREAD

**Issue by divijjain** [CargoSense/absinthe_client#15]
Because the lock depends on swoosh 1.14.2 which depends on req ~> 0.4 or ~> 1.0, the lock requires req ~> 0.4 or ~> 1.0.
And because every version of absinthe_client depends on req ~> 0.3.0, the lock is incompatible with absinthe_client.
And because your app depends on the lock, no version of absinthe_client is allowed.
So, because your app depends on absinthe_client ~> 0.1.0, version solving failed.

**Comment by Oliphaunte** [comment]
https://github.com/CargoSense/absinthe_client/pull/14 addresses the issue, just need a new release for it.

In the meantime, you can set swoosh to ~> 1.14.0

**Comment by Oliphaunte** [comment]
@mcrumm Sorry to ping, would it be possible to get a new release for this with the latest updates?

**Comment by mcrumm** [comment]
v0.1.1 has been released :)
